/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VueRouteImport } from './routes/vue'
import { Route as VanillaRouteImport } from './routes/vanilla'
import { Route as SvelteRouteImport } from './routes/svelte'
import { Route as ReactRouteImport } from './routes/react'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShowcasesIndexRouteImport } from './routes/showcases.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as TestXlsxRouteImport } from './routes/test.xlsx'
import { Route as TestSemanticGridRouteImport } from './routes/test.semantic-grid'
import { Route as TestRenderersRouteImport } from './routes/test.renderers'
import { Route as TestPrefetchRouteImport } from './routes/test.prefetch'
import { Route as TestFormulasEngineRouteImport } from './routes/test.formulas-engine'
import { Route as TestCollaborationRouteImport } from './routes/test.collaboration'
import { Route as ShowcasesPerformanceRouteImport } from './routes/showcases.performance'
import { Route as ShowcasesInteroperabilityRouteImport } from './routes/showcases.interoperability'
import { Route as ShowcasesHostRowsRouteImport } from './routes/showcases.host-rows'
import { Route as ShowcasesEngineRouteImport } from './routes/showcases.engine'
import { Route as ShowcasesDatabaseRouteImport } from './routes/showcases.database'
import { Route as ShowcasesCollaborationRouteImport } from './routes/showcases.collaboration'
import { Route as DocsProofRouteImport } from './routes/docs.proof'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as TestFrameworkLifecycleFrameworkRouteImport } from './routes/test.framework-lifecycle.$framework'

const VueRoute = VueRouteImport.update({
  id: '/vue',
  path: '/vue',
  getParentRoute: () => rootRouteImport,
} as any)
const VanillaRoute = VanillaRouteImport.update({
  id: '/vanilla',
  path: '/vanilla',
  getParentRoute: () => rootRouteImport,
} as any)
const SvelteRoute = SvelteRouteImport.update({
  id: '/svelte',
  path: '/svelte',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactRoute = ReactRouteImport.update({
  id: '/react',
  path: '/react',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcasesIndexRoute = ShowcasesIndexRouteImport.update({
  id: '/showcases/',
  path: '/showcases/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestXlsxRoute = TestXlsxRouteImport.update({
  id: '/test/xlsx',
  path: '/test/xlsx',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSemanticGridRoute = TestSemanticGridRouteImport.update({
  id: '/test/semantic-grid',
  path: '/test/semantic-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRenderersRoute = TestRenderersRouteImport.update({
  id: '/test/renderers',
  path: '/test/renderers',
  getParentRoute: () => rootRouteImport,
} as any)
const TestPrefetchRoute = TestPrefetchRouteImport.update({
  id: '/test/prefetch',
  path: '/test/prefetch',
  getParentRoute: () => rootRouteImport,
} as any)
const TestFormulasEngineRoute = TestFormulasEngineRouteImport.update({
  id: '/test/formulas-engine',
  path: '/test/formulas-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCollaborationRoute = TestCollaborationRouteImport.update({
  id: '/test/collaboration',
  path: '/test/collaboration',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcasesPerformanceRoute = ShowcasesPerformanceRouteImport.update({
  id: '/showcases/performance',
  path: '/showcases/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcasesInteroperabilityRoute =
  ShowcasesInteroperabilityRouteImport.update({
    id: '/showcases/interoperability',
    path: '/showcases/interoperability',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowcasesHostRowsRoute = ShowcasesHostRowsRouteImport.update({
  id: '/showcases/host-rows',
  path: '/showcases/host-rows',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcasesEngineRoute = ShowcasesEngineRouteImport.update({
  id: '/showcases/engine',
  path: '/showcases/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcasesDatabaseRoute = ShowcasesDatabaseRouteImport.update({
  id: '/showcases/database',
  path: '/showcases/database',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcasesCollaborationRoute = ShowcasesCollaborationRouteImport.update({
  id: '/showcases/collaboration',
  path: '/showcases/collaboration',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsProofRoute = DocsProofRouteImport.update({
  id: '/docs/proof',
  path: '/docs/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TestFrameworkLifecycleFrameworkRoute =
  TestFrameworkLifecycleFrameworkRouteImport.update({
    id: '/test/framework-lifecycle/$framework',
    path: '/test/framework-lifecycle/$framework',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/react': typeof ReactRoute
  '/svelte': typeof SvelteRoute
  '/vanilla': typeof VanillaRoute
  '/vue': typeof VueRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/proof': typeof DocsProofRoute
  '/showcases/collaboration': typeof ShowcasesCollaborationRoute
  '/showcases/database': typeof ShowcasesDatabaseRoute
  '/showcases/engine': typeof ShowcasesEngineRoute
  '/showcases/host-rows': typeof ShowcasesHostRowsRoute
  '/showcases/interoperability': typeof ShowcasesInteroperabilityRoute
  '/showcases/performance': typeof ShowcasesPerformanceRoute
  '/test/collaboration': typeof TestCollaborationRoute
  '/test/formulas-engine': typeof TestFormulasEngineRoute
  '/test/prefetch': typeof TestPrefetchRoute
  '/test/renderers': typeof TestRenderersRoute
  '/test/semantic-grid': typeof TestSemanticGridRoute
  '/test/xlsx': typeof TestXlsxRoute
  '/docs/': typeof DocsIndexRoute
  '/showcases/': typeof ShowcasesIndexRoute
  '/test/framework-lifecycle/$framework': typeof TestFrameworkLifecycleFrameworkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/react': typeof ReactRoute
  '/svelte': typeof SvelteRoute
  '/vanilla': typeof VanillaRoute
  '/vue': typeof VueRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/proof': typeof DocsProofRoute
  '/showcases/collaboration': typeof ShowcasesCollaborationRoute
  '/showcases/database': typeof ShowcasesDatabaseRoute
  '/showcases/engine': typeof ShowcasesEngineRoute
  '/showcases/host-rows': typeof ShowcasesHostRowsRoute
  '/showcases/interoperability': typeof ShowcasesInteroperabilityRoute
  '/showcases/performance': typeof ShowcasesPerformanceRoute
  '/test/collaboration': typeof TestCollaborationRoute
  '/test/formulas-engine': typeof TestFormulasEngineRoute
  '/test/prefetch': typeof TestPrefetchRoute
  '/test/renderers': typeof TestRenderersRoute
  '/test/semantic-grid': typeof TestSemanticGridRoute
  '/test/xlsx': typeof TestXlsxRoute
  '/docs': typeof DocsIndexRoute
  '/showcases': typeof ShowcasesIndexRoute
  '/test/framework-lifecycle/$framework': typeof TestFrameworkLifecycleFrameworkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/react': typeof ReactRoute
  '/svelte': typeof SvelteRoute
  '/vanilla': typeof VanillaRoute
  '/vue': typeof VueRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/proof': typeof DocsProofRoute
  '/showcases/collaboration': typeof ShowcasesCollaborationRoute
  '/showcases/database': typeof ShowcasesDatabaseRoute
  '/showcases/engine': typeof ShowcasesEngineRoute
  '/showcases/host-rows': typeof ShowcasesHostRowsRoute
  '/showcases/interoperability': typeof ShowcasesInteroperabilityRoute
  '/showcases/performance': typeof ShowcasesPerformanceRoute
  '/test/collaboration': typeof TestCollaborationRoute
  '/test/formulas-engine': typeof TestFormulasEngineRoute
  '/test/prefetch': typeof TestPrefetchRoute
  '/test/renderers': typeof TestRenderersRoute
  '/test/semantic-grid': typeof TestSemanticGridRoute
  '/test/xlsx': typeof TestXlsxRoute
  '/docs/': typeof DocsIndexRoute
  '/showcases/': typeof ShowcasesIndexRoute
  '/test/framework-lifecycle/$framework': typeof TestFrameworkLifecycleFrameworkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/react'
    | '/svelte'
    | '/vanilla'
    | '/vue'
    | '/docs/$'
    | '/docs/proof'
    | '/showcases/collaboration'
    | '/showcases/database'
    | '/showcases/engine'
    | '/showcases/host-rows'
    | '/showcases/interoperability'
    | '/showcases/performance'
    | '/test/collaboration'
    | '/test/formulas-engine'
    | '/test/prefetch'
    | '/test/renderers'
    | '/test/semantic-grid'
    | '/test/xlsx'
    | '/docs/'
    | '/showcases/'
    | '/test/framework-lifecycle/$framework'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/react'
    | '/svelte'
    | '/vanilla'
    | '/vue'
    | '/docs/$'
    | '/docs/proof'
    | '/showcases/collaboration'
    | '/showcases/database'
    | '/showcases/engine'
    | '/showcases/host-rows'
    | '/showcases/interoperability'
    | '/showcases/performance'
    | '/test/collaboration'
    | '/test/formulas-engine'
    | '/test/prefetch'
    | '/test/renderers'
    | '/test/semantic-grid'
    | '/test/xlsx'
    | '/docs'
    | '/showcases'
    | '/test/framework-lifecycle/$framework'
  id:
    | '__root__'
    | '/'
    | '/react'
    | '/svelte'
    | '/vanilla'
    | '/vue'
    | '/docs/$'
    | '/docs/proof'
    | '/showcases/collaboration'
    | '/showcases/database'
    | '/showcases/engine'
    | '/showcases/host-rows'
    | '/showcases/interoperability'
    | '/showcases/performance'
    | '/test/collaboration'
    | '/test/formulas-engine'
    | '/test/prefetch'
    | '/test/renderers'
    | '/test/semantic-grid'
    | '/test/xlsx'
    | '/docs/'
    | '/showcases/'
    | '/test/framework-lifecycle/$framework'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReactRoute: typeof ReactRoute
  SvelteRoute: typeof SvelteRoute
  VanillaRoute: typeof VanillaRoute
  VueRoute: typeof VueRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsProofRoute: typeof DocsProofRoute
  ShowcasesCollaborationRoute: typeof ShowcasesCollaborationRoute
  ShowcasesDatabaseRoute: typeof ShowcasesDatabaseRoute
  ShowcasesEngineRoute: typeof ShowcasesEngineRoute
  ShowcasesHostRowsRoute: typeof ShowcasesHostRowsRoute
  ShowcasesInteroperabilityRoute: typeof ShowcasesInteroperabilityRoute
  ShowcasesPerformanceRoute: typeof ShowcasesPerformanceRoute
  TestCollaborationRoute: typeof TestCollaborationRoute
  TestFormulasEngineRoute: typeof TestFormulasEngineRoute
  TestPrefetchRoute: typeof TestPrefetchRoute
  TestRenderersRoute: typeof TestRenderersRoute
  TestSemanticGridRoute: typeof TestSemanticGridRoute
  TestXlsxRoute: typeof TestXlsxRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ShowcasesIndexRoute: typeof ShowcasesIndexRoute
  TestFrameworkLifecycleFrameworkRoute: typeof TestFrameworkLifecycleFrameworkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vue': {
      id: '/vue'
      path: '/vue'
      fullPath: '/vue'
      preLoaderRoute: typeof VueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vanilla': {
      id: '/vanilla'
      path: '/vanilla'
      fullPath: '/vanilla'
      preLoaderRoute: typeof VanillaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/svelte': {
      id: '/svelte'
      path: '/svelte'
      fullPath: '/svelte'
      preLoaderRoute: typeof SvelteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react': {
      id: '/react'
      path: '/react'
      fullPath: '/react'
      preLoaderRoute: typeof ReactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcases/': {
      id: '/showcases/'
      path: '/showcases'
      fullPath: '/showcases/'
      preLoaderRoute: typeof ShowcasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/xlsx': {
      id: '/test/xlsx'
      path: '/test/xlsx'
      fullPath: '/test/xlsx'
      preLoaderRoute: typeof TestXlsxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/semantic-grid': {
      id: '/test/semantic-grid'
      path: '/test/semantic-grid'
      fullPath: '/test/semantic-grid'
      preLoaderRoute: typeof TestSemanticGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/renderers': {
      id: '/test/renderers'
      path: '/test/renderers'
      fullPath: '/test/renderers'
      preLoaderRoute: typeof TestRenderersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/prefetch': {
      id: '/test/prefetch'
      path: '/test/prefetch'
      fullPath: '/test/prefetch'
      preLoaderRoute: typeof TestPrefetchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/formulas-engine': {
      id: '/test/formulas-engine'
      path: '/test/formulas-engine'
      fullPath: '/test/formulas-engine'
      preLoaderRoute: typeof TestFormulasEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/collaboration': {
      id: '/test/collaboration'
      path: '/test/collaboration'
      fullPath: '/test/collaboration'
      preLoaderRoute: typeof TestCollaborationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcases/performance': {
      id: '/showcases/performance'
      path: '/showcases/performance'
      fullPath: '/showcases/performance'
      preLoaderRoute: typeof ShowcasesPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcases/interoperability': {
      id: '/showcases/interoperability'
      path: '/showcases/interoperability'
      fullPath: '/showcases/interoperability'
      preLoaderRoute: typeof ShowcasesInteroperabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcases/host-rows': {
      id: '/showcases/host-rows'
      path: '/showcases/host-rows'
      fullPath: '/showcases/host-rows'
      preLoaderRoute: typeof ShowcasesHostRowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcases/engine': {
      id: '/showcases/engine'
      path: '/showcases/engine'
      fullPath: '/showcases/engine'
      preLoaderRoute: typeof ShowcasesEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcases/database': {
      id: '/showcases/database'
      path: '/showcases/database'
      fullPath: '/showcases/database'
      preLoaderRoute: typeof ShowcasesDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcases/collaboration': {
      id: '/showcases/collaboration'
      path: '/showcases/collaboration'
      fullPath: '/showcases/collaboration'
      preLoaderRoute: typeof ShowcasesCollaborationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/proof': {
      id: '/docs/proof'
      path: '/docs/proof'
      fullPath: '/docs/proof'
      preLoaderRoute: typeof DocsProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/framework-lifecycle/$framework': {
      id: '/test/framework-lifecycle/$framework'
      path: '/test/framework-lifecycle/$framework'
      fullPath: '/test/framework-lifecycle/$framework'
      preLoaderRoute: typeof TestFrameworkLifecycleFrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReactRoute: ReactRoute,
  SvelteRoute: SvelteRoute,
  VanillaRoute: VanillaRoute,
  VueRoute: VueRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsProofRoute: DocsProofRoute,
  ShowcasesCollaborationRoute: ShowcasesCollaborationRoute,
  ShowcasesDatabaseRoute: ShowcasesDatabaseRoute,
  ShowcasesEngineRoute: ShowcasesEngineRoute,
  ShowcasesHostRowsRoute: ShowcasesHostRowsRoute,
  ShowcasesInteroperabilityRoute: ShowcasesInteroperabilityRoute,
  ShowcasesPerformanceRoute: ShowcasesPerformanceRoute,
  TestCollaborationRoute: TestCollaborationRoute,
  TestFormulasEngineRoute: TestFormulasEngineRoute,
  TestPrefetchRoute: TestPrefetchRoute,
  TestRenderersRoute: TestRenderersRoute,
  TestSemanticGridRoute: TestSemanticGridRoute,
  TestXlsxRoute: TestXlsxRoute,
  DocsIndexRoute: DocsIndexRoute,
  ShowcasesIndexRoute: ShowcasesIndexRoute,
  TestFrameworkLifecycleFrameworkRoute: TestFrameworkLifecycleFrameworkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
